name: Deploy to Docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build all services
        run: |
          cd api-gateway && mvn clean package -DskipTests && cd ..
          cd user-service && mvn clean package -DskipTests && cd ..
          cd product-service && mvn clean package -DskipTests && cd ..
          cd cart-service && mvn clean package -DskipTests && cd ..
          cd order-service && mvn clean package -DskipTests && cd ..
          cd wishlist-service && mvn clean package -DskipTests && cd ..
          cd notification-service && mvn clean package -DskipTests && cd ..

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker images
#        run: |
#          docker compose build
#          docker compose push

      - name: Deploy to server (optional)
        run: |
          echo "Deployment step - configure your server here"
          # Например, можно использовать SSH для деплоя на сервер
          # или просто оставить локальный docker compose up
