name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test API Gateway
        run: |
          cd api-gateway
          mvn clean test

      - name: Test User Service
        run: |
          cd user-service
          mvn clean test

      - name: Test Product Service
        run: |
          cd product-service
          mvn clean test

      - name: Test Cart Service
        run: |
          cd cart-service
          mvn clean test

      - name: Test Order Service
        run: |
          cd order-service
          mvn clean test

      - name: Test Wishlist Service
        run: |
          cd wishlist-service
          mvn clean test

      - name: Test Notification Service
        run: |
          cd notification-service
          mvn clean test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'
