name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run all tests
        run: |
          for service in api-gateway user-service product-service cart-service order-service wishlist-service notification-service; do
            echo "Testing $service..."
            cd $service
            mvn clean test -Dtest=!*ApplicationTests || exit 1
            cd ..
          done

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'
          retention-days: 7
